"""LinkForge Core Library.

The platform-independent heart of the LinkForge project, providing a
unified Intermediate Representation (IR) for robotics. This core library
handles the "Robotics Intelligence" isolated from design tools.

Modules:
    composer: High-level API for assembling robots via RobotBuilder.
    generators: URDF, XACRO, and SRDF file generation.
    models: Core data structures for robots, links, joints, and geometry.
    parsers: Lossless URDF, XACRO, and SRDF file parsing.
    physics: Scientifically grounded inertia and mass calculations.
    validation: Multi-phase hardened validation of robot descriptions.
"""

from __future__ import annotations

__version__ = "1.3.0"  # x-release-please-version

from . import composer, generators, models, parsers, physics, validation

# 2. Base Interfaces and Resolvers
from .base import (
    FileSystemResolver,
    IResourceResolver,
    NetworkResolver,
    RobotGenerator,
    RobotParser,
)

# 8. Composer API (Helpers)
from .composer import (
    LinkBuilder,
    RobotBuilder,
    box,
    cylinder,
    mesh,
    sphere,
)

# 1. Constants and Numerical Infrastructure
from .constants import (
    CAM_FORMAT_BAYER_BGGR8,
    CAM_FORMAT_BAYER_RGGB8,
    CAM_FORMAT_GRAY8,
    CAM_FORMAT_GRAY16,
    CAM_FORMAT_RGB8,
    CAM_FORMAT_RGB16,
    CONTROL_TYPE_ACTUATOR,
    CONTROL_TYPE_SENSOR,
    CONTROL_TYPE_SYSTEM,
    DEFAULT_AXIS_XYZ,
    DEFAULT_AXIS_XYZ_STR,
    DEFAULT_CAMERA_FAR,
    DEFAULT_CAMERA_FORMAT,
    DEFAULT_CAMERA_FOV,
    DEFAULT_CAMERA_HEIGHT,
    DEFAULT_CAMERA_NEAR,
    DEFAULT_CAMERA_WIDTH,
    DEFAULT_CONTACT_KD,
    DEFAULT_CONTACT_KP,
    DEFAULT_FRICTION_MU,
    DEFAULT_FRICTION_MU2,
    DEFAULT_GRAVITY,
    DEFAULT_JOINT_DAMPING,
    DEFAULT_JOINT_EFFORT,
    DEFAULT_JOINT_FRICTION,
    DEFAULT_JOINT_TYPE,
    DEFAULT_JOINT_VELOCITY,
    DEFAULT_LIDAR_MAX_ANGLE,
    DEFAULT_LIDAR_MIN_ANGLE,
    DEFAULT_LIDAR_RANGE_MAX,
    DEFAULT_LIDAR_RANGE_MIN,
    DEFAULT_LIDAR_RANGE_RESOLUTION,
    DEFAULT_LIDAR_SAMPLES,
    DEFAULT_LIDAR_VERTICAL_MAX_ANGLE,
    DEFAULT_LIDAR_VERTICAL_MIN_ANGLE,
    DEFAULT_LIDAR_VERTICAL_SAMPLES,
    DEFAULT_LINK_MASS,
    DEFAULT_MATERIAL_RGBA,
    DEFAULT_MATERIAL_RGBA_STR,
    DEFAULT_SELF_COLLIDE,
    DEFAULT_SENSOR_ALWAYS_ON,
    DEFAULT_SENSOR_TYPE,
    DEFAULT_SENSOR_VISUALIZE,
    DEFAULT_UPDATE_RATE,
    EPSILON,
    GEOM_BOX,
    GEOM_CYLINDER,
    GEOM_EPSILON,
    GEOM_MESH,
    GEOM_SPHERE,
    HW_IF_EFFORT,
    HW_IF_POSITION,
    HW_IF_VELOCITY,
    JOINT_CONTINUOUS,
    JOINT_FIXED,
    JOINT_FLOATING,
    JOINT_PLANAR,
    JOINT_PRISMATIC,
    JOINT_REVOLUTE,
    MAX_REASONABLE_FLOAT,
    MAX_REASONABLE_INT,
    MAX_XML_DEPTH,
    MIN_REASONABLE_INERTIA,
    MIN_REASONABLE_MASS,
    NOISE_GAUSSIAN,
    NOISE_GAUSSIAN_QUANTIZED,
    PI,
    ROS2_CONTROL_DEFAULT_GAZEBO_PLUGIN,
    ROS2_CONTROL_DEFAULT_PLUGIN,
    SENSOR_CAMERA,
    SENSOR_CONTACT,
    SENSOR_DEPTH_CAMERA,
    SENSOR_FORCE_TORQUE,
    SENSOR_GPS,
    SENSOR_GPU_LIDAR,
    SENSOR_IMU,
    SENSOR_LIDAR,
    SRDF_VJOIN_FIXED,
    SRDF_VJOIN_FLOATING,
    SRDF_VJOIN_PLANAR,
    SYLVESTER_TOLERANCE_EPSILON,
    TRANS_CUSTOM,
    TRANS_DIFFERENTIAL,
    TRANS_FOUR_BAR,
    TRANS_SIMPLE,
)

# 3. Exceptions and Error Codes
from .exceptions import (
    LinkForgeError,
    RobotGeneratorError,
    RobotMathError,
    RobotModelError,
    RobotParserError,
    RobotParserIOError,
    RobotPhysicsError,
    RobotSecurityError,
    RobotValidationError,
    RobotXacroError,
    RobotXacroExpressionError,
    RobotXacroRecursionError,
    ValidationErrorCode,
    XacroDetectedError,
)

# 5. Parsers and Generators
from .generators import (
    RobotXMLGenerator,
    SRDFGenerator,
    URDFGenerator,
    XACROGenerator,
)

# 9. Logging
from .logging_config import get_logger, setup_logging

# 4. Models and Data Structures
from .models import (
    Box,
    CameraInfo,
    Chain,
    Collision,
    CollisionPair,
    Color,
    ContactInfo,
    Cylinder,
    EndEffector,
    ForceTorqueInfo,
    GazeboElement,
    GazeboPlugin,
    Geometry,
    GeometryType,
    GPSInfo,
    GroupState,
    IMUInfo,
    Inertial,
    InertiaTensor,
    Joint,
    JointCalibration,
    JointDynamics,
    JointLimits,
    JointMimic,
    JointProperty,
    JointSafetyController,
    JointType,
    KinematicGraph,
    LidarInfo,
    Link,
    LinkPhysics,
    LinkSphereApproximation,
    Material,
    Mesh,
    PassiveJoint,
    PlanningGroup,
    Robot,
    Ros2Control,
    Ros2ControlJoint,
    Ros2ControlSensor,
    SemanticRobotDescription,
    Sensor,
    SensorNoise,
    SensorType,
    Sphere,
    SrdfSphere,
    Transform,
    Transmission,
    TransmissionActuator,
    TransmissionJoint,
    TransmissionType,
    Vector3,
    VirtualJoint,
    Visual,
)
from .parsers import (
    RobotXMLParser,
    SRDFParser,
    URDFParser,
    XACROParser,
    XacroResolver,
    clear_xacro_cache,
)

# 6. Physics and Math Utilities
from .physics import (
    calculate_box_inertia,
    calculate_cylinder_inertia,
    calculate_inertia,
    calculate_mesh_inertia_approximation,
    calculate_mesh_inertia_from_triangles,
    calculate_sphere_inertia,
    validate_mesh_topology,
)
from .utils.dict_utils import AttrDict, filter_items_by_name
from .utils.math_utils import (
    clean_float,
    format_float,
    format_vector,
    normalize_vector,
)
from .utils.path_utils import (
    _extract_package_name,
    get_export_path,
    normalize_uri_to_path,
    resolve_package_path,
)
from .utils.string_utils import (
    format_scientific,
    is_valid_name,
    parse_scientific,
    sanitize_name,
)
from .utils.xml_utils import (
    create_xml_element,
    parse_float,
    parse_int,
    parse_optional_bool,
    parse_optional_float,
    parse_vector3,
    serialize_xml,
    validate_xml_depth,
    xml_add_text,
    xml_add_vector,
)

# 7. Validation and Security
from .validation import (
    DuplicateNameCheck,
    GeometryCheck,
    HasLinksCheck,
    JointReferenceCheck,
    MassPropertiesCheck,
    MimicChainCheck,
    RobotValidator,
    Ros2ControlCheck,
    SemanticCheck,
    Severity,
    TreeStructureCheck,
    ValidationCheck,
    ValidationIssue,
    ValidationResult,
    find_sandbox_root,
    is_suspicious_location,
    validate_mesh_path,
    validate_package_uri,
)

__all__ = [
    # Sub-Packages
    "composer",
    "generators",
    "models",
    "parsers",
    "physics",
    "validation",
    # Core Entities
    "Robot",
    "Link",
    "Joint",
    "JointLimits",
    "JointDynamics",
    "JointMimic",
    "JointSafetyController",
    "JointCalibration",
    "JointType",
    "Transform",
    "InertiaTensor",
    "Inertial",
    "Visual",
    "Collision",
    "KinematicGraph",
    "LinkPhysics",
    # Geometry and Materials
    "Box",
    "Cylinder",
    "Sphere",
    "Mesh",
    "Geometry",
    "GeometryType",
    "Material",
    "Color",
    "Vector3",
    # Sensors and Hardware
    "Sensor",
    "SensorType",
    "SensorNoise",
    "LidarInfo",
    "CameraInfo",
    "IMUInfo",
    "GPSInfo",
    "ContactInfo",
    "ForceTorqueInfo",
    # Transmission and Control
    "Transmission",
    "TransmissionType",
    "TransmissionJoint",
    "TransmissionActuator",
    "Ros2ControlJoint",
    "Ros2ControlSensor",
    # Gazebo Integration
    "GazeboPlugin",
    "GazeboElement",
    # Semantic API (SRDF)
    "SemanticRobotDescription",
    "PlanningGroup",
    "Chain",
    "GroupState",
    "EndEffector",
    "PassiveJoint",
    "VirtualJoint",
    "CollisionPair",
    "LinkSphereApproximation",
    "SrdfSphere",
    "JointProperty",
    # Robotics Logic (IO & Validation)
    "RobotValidator",
    "RobotXMLParser",
    "RobotGenerator",
    "Ros2Control",
    "RobotParser",
    "URDFParser",
    "XACROParser",
    "SRDFParser",
    "URDFGenerator",
    "RobotXMLGenerator",
    "XACROGenerator",
    "SRDFGenerator",
    "ValidationCheck",
    "DuplicateNameCheck",
    "GeometryCheck",
    "HasLinksCheck",
    "JointReferenceCheck",
    "MassPropertiesCheck",
    "MimicChainCheck",
    "Ros2ControlCheck",
    "TreeStructureCheck",
    "ValidationResult",
    "ValidationIssue",
    "Severity",
    "XacroResolver",
    "clear_xacro_cache",
    "SemanticCheck",
    "find_sandbox_root",
    "is_suspicious_location",
    "validate_mesh_path",
    "validate_package_uri",
    "NetworkResolver",
    "FileSystemResolver",
    "IResourceResolver",
    "MAX_XML_DEPTH",
    "MAX_REASONABLE_FLOAT",
    "MAX_REASONABLE_INT",
    # Composer API
    "RobotBuilder",
    "LinkBuilder",
    "box",
    "cylinder",
    "sphere",
    "mesh",
    # Physics and Math
    "calculate_inertia",
    "calculate_box_inertia",
    "calculate_cylinder_inertia",
    "calculate_sphere_inertia",
    "calculate_mesh_inertia_approximation",
    "calculate_mesh_inertia_from_triangles",
    "validate_mesh_topology",
    "clean_float",
    "format_float",
    "normalize_vector",
    "format_vector",
    "format_scientific",
    "parse_scientific",
    # Utilities
    "get_logger",
    "setup_logging",
    "sanitize_name",
    "is_valid_name",
    "filter_items_by_name",
    "AttrDict",
    "resolve_package_path",
    "normalize_uri_to_path",
    "get_export_path",
    "_extract_package_name",
    "serialize_xml",
    "validate_xml_depth",
    "parse_optional_bool",
    "parse_optional_float",
    "xml_add_text",
    "xml_add_vector",
    "create_xml_element",
    "parse_float",
    "parse_int",
    "parse_vector3",
    # Constants
    "PI",
    "EPSILON",
    "GEOM_EPSILON",
    "MIN_REASONABLE_MASS",
    "MIN_REASONABLE_INERTIA",
    "SYLVESTER_TOLERANCE_EPSILON",
    "GEOM_BOX",
    "GEOM_CYLINDER",
    "GEOM_SPHERE",
    "GEOM_MESH",
    "JOINT_REVOLUTE",
    "JOINT_CONTINUOUS",
    "JOINT_PRISMATIC",
    "JOINT_FIXED",
    "JOINT_FLOATING",
    "JOINT_PLANAR",
    "DEFAULT_JOINT_TYPE",
    "DEFAULT_JOINT_EFFORT",
    "DEFAULT_JOINT_VELOCITY",
    "DEFAULT_JOINT_DAMPING",
    "DEFAULT_JOINT_FRICTION",
    "DEFAULT_LINK_MASS",
    "DEFAULT_GRAVITY",
    "DEFAULT_SELF_COLLIDE",
    "DEFAULT_FRICTION_MU",
    "DEFAULT_FRICTION_MU2",
    "DEFAULT_CONTACT_KP",
    "DEFAULT_CONTACT_KD",
    "DEFAULT_AXIS_XYZ",
    "DEFAULT_AXIS_XYZ_STR",
    "DEFAULT_UPDATE_RATE",
    "DEFAULT_SENSOR_ALWAYS_ON",
    "DEFAULT_SENSOR_VISUALIZE",
    "DEFAULT_CAMERA_FOV",
    "DEFAULT_CAMERA_WIDTH",
    "DEFAULT_CAMERA_HEIGHT",
    "DEFAULT_CAMERA_NEAR",
    "DEFAULT_CAMERA_FAR",
    "DEFAULT_CAMERA_FORMAT",
    "DEFAULT_LIDAR_SAMPLES",
    "DEFAULT_LIDAR_MIN_ANGLE",
    "DEFAULT_LIDAR_MAX_ANGLE",
    "DEFAULT_LIDAR_RANGE_MIN",
    "DEFAULT_LIDAR_RANGE_MAX",
    "DEFAULT_LIDAR_RANGE_RESOLUTION",
    "DEFAULT_LIDAR_VERTICAL_SAMPLES",
    "DEFAULT_LIDAR_VERTICAL_MIN_ANGLE",
    "DEFAULT_LIDAR_VERTICAL_MAX_ANGLE",
    "CAM_FORMAT_RGB8",
    "CAM_FORMAT_RGB16",
    "CAM_FORMAT_GRAY8",
    "CAM_FORMAT_GRAY16",
    "CAM_FORMAT_BAYER_RGGB8",
    "CAM_FORMAT_BAYER_BGGR8",
    "NOISE_GAUSSIAN",
    "NOISE_GAUSSIAN_QUANTIZED",
    "ROS2_CONTROL_DEFAULT_PLUGIN",
    "ROS2_CONTROL_DEFAULT_GAZEBO_PLUGIN",
    "DEFAULT_MATERIAL_RGBA",
    "DEFAULT_MATERIAL_RGBA_STR",
    "DEFAULT_SENSOR_TYPE",
    "SENSOR_CAMERA",
    "SENSOR_DEPTH_CAMERA",
    "SENSOR_LIDAR",
    "SENSOR_GPU_LIDAR",
    "SENSOR_IMU",
    "SENSOR_GPS",
    "SENSOR_CONTACT",
    "SENSOR_FORCE_TORQUE",
    "HW_IF_POSITION",
    "HW_IF_VELOCITY",
    "HW_IF_EFFORT",
    "CONTROL_TYPE_SYSTEM",
    "CONTROL_TYPE_ACTUATOR",
    "CONTROL_TYPE_SENSOR",
    "TRANS_SIMPLE",
    "TRANS_DIFFERENTIAL",
    "TRANS_FOUR_BAR",
    "TRANS_CUSTOM",
    "SRDF_VJOIN_FIXED",
    "SRDF_VJOIN_PLANAR",
    "SRDF_VJOIN_FLOATING",
    # Exceptions
    "LinkForgeError",
    "RobotGeneratorError",
    "RobotModelError",
    "RobotParserError",
    "RobotParserIOError",
    "RobotPhysicsError",
    "RobotValidationError",
    "RobotMathError",
    "RobotSecurityError",
    "RobotXacroError",
    "RobotXacroRecursionError",
    "RobotXacroExpressionError",
    "ValidationErrorCode",
    "XacroDetectedError",
]
