"""Unit tests verifying deterministic exports for URDF, SRDF, and XACRO."""

import time

from linkforge.core import RobotBuilder, box, cylinder
from linkforge.core.generators.srdf_generator import SRDFGenerator
from linkforge.core.generators.urdf_generator import URDFGenerator
from linkforge.core.generators.xacro_generator import XACROGenerator
from linkforge.core.models.gazebo import GazeboElement, GazeboPlugin
from linkforge.core.models.ros2_control import Ros2Control, Ros2ControlJoint
from linkforge.core.models.srdf import (
    GroupState,
    PlanningGroup,
    SemanticRobotDescription,
    VirtualJoint,
)


def _create_test_robot() -> RobotBuilder:
    builder = RobotBuilder("test_arm")
    builder.link("base_link").visual(box(0.5, 0.5, 0.1)).collision().mass(5.0).root()
    builder.link("link_b", parent="base_link").visual(
        cylinder(radius=0.05, length=0.4), xyz=(0, 0, 0.2)
    ).collision().mass(1.0).revolute(axis=(0, 0, 1), limits=(-3.14, 3.14))
    builder.link("link_a", parent="link_b").visual(
        cylinder(radius=0.05, length=0.4), xyz=(0, 0, 0.4)
    ).collision().mass(1.0).revolute(axis=(0, 1, 0), limits=(-1.57, 1.57))
    return builder


def test_urdf_export_deterministic_across_time() -> None:
    """Verify URDF export produces identical bytes regardless of execution time."""
    builder = _create_test_robot()
    robot = builder.build()

    generator = URDFGenerator()
    out1 = generator.generate(robot)
    time.sleep(0.01)
    out2 = generator.generate(robot)

    assert out1 == out2
    assert "Date:" not in out1
    assert "Generated by: LinkForge\n" in out1


def test_urdf_ros2_control_and_plugin_sorting() -> None:
    """Verify ROS 2 Control joint parameters and Gazebo plugin parameters are sorted."""
    builder = _create_test_robot()
    robot = builder.build()

    # Add ros2_controls with unsorted parameter dicts
    joint_with_params = Ros2ControlJoint(
        name=robot.joints[0].name,
        command_interfaces=["position"],
        state_interfaces=["position"],
        parameters={"zeta": "1.0", "alpha": "0.5", "beta": "2.0"},
    )
    rc = Ros2Control(
        name="test_control",
        type="system",
        hardware_plugin="test/Hardware",
        parameters={"param_z": "10", "param_a": "1"},
        joints=[joint_with_params],
    )
    robot.ros2_controls = (rc,)

    gz = GazeboElement(
        reference="base_link",
        plugins=[
            GazeboPlugin(
                name="my_plugin",
                filename="libmy_plugin.so",
                parameters={"z_factor": "100", "a_factor": "200"},
            )
        ],
    )
    robot.gazebo_elements = (gz,)

    out = URDFGenerator().generate(robot)

    # Check hardware params order
    idx_a = out.find('name="param_a"')
    idx_z = out.find('name="param_z"')
    assert idx_a != -1 and idx_z != -1
    assert idx_a < idx_z

    # Check joint params order
    idx_alpha = out.find('name="alpha"')
    idx_beta = out.find('name="beta"')
    idx_zeta = out.find('name="zeta"')
    assert idx_alpha != -1 and idx_beta != -1 and idx_zeta != -1
    assert idx_alpha < idx_beta < idx_zeta

    # Check plugin params order
    idx_afactor = out.find("<a_factor>200</a_factor>")
    idx_zfactor = out.find("<z_factor>100</z_factor>")
    assert idx_afactor != -1 and idx_zfactor != -1
    assert idx_afactor < idx_zfactor


def test_srdf_group_state_joint_sorting() -> None:
    """Verify SRDF group_state joint order is sorted regardless of dictionary insertion order."""
    builder = _create_test_robot()
    robot = builder.build()

    j1, j2 = sorted([robot.joints[0].name, robot.joints[1].name])

    # Dictionary with keys inserted in reverse order
    state1 = GroupState(
        name="pose1",
        group="arm",
        joint_values={j2: [0.5], j1: [-0.5]},
    )
    # Dictionary with keys inserted in forward order
    state2 = GroupState(
        name="pose1",
        group="arm",
        joint_values={j1: [-0.5], j2: [0.5]},
    )

    robot.semantic = SemanticRobotDescription(
        robot_name="test_arm",
        virtual_joints=[VirtualJoint("world_joint", "fixed", "world", "base_link")],
        groups=[PlanningGroup("arm", joints=(j1, j2))],
        group_states=[state1],
    )
    out1 = SRDFGenerator().generate(robot)

    robot.semantic = SemanticRobotDescription(
        robot_name="test_arm",
        virtual_joints=[VirtualJoint("world_joint", "fixed", "world", "base_link")],
        groups=[PlanningGroup("arm", joints=(j1, j2))],
        group_states=[state2],
    )
    out2 = SRDFGenerator().generate(robot)

    assert out1 == out2
    assert "Date:" not in out1
    assert "Generated by: LinkForge\n" in out1

    # Check joints in state are alphabetical
    idx_j1 = out1.find(f'name="{j1}"')
    idx_j2 = out1.find(f'name="{j2}"')
    assert idx_j1 < idx_j2


def test_xacro_deterministic_output() -> None:
    """Verify XACRO generation is deterministic across multiple calls with macros and dimensions."""
    builder = RobotBuilder("xacro_bot")
    builder.link("base").visual(box(0.2, 0.2, 0.2)).collision().mass(1.0).root()
    # 4 identical wheel links to trigger macro & dimension grouping
    for i in range(4):
        builder.link(f"wheel_{i}", parent="base").visual(
            cylinder(radius=0.08, length=0.04), xyz=(0.1 * i, 0.1, 0)
        ).collision().mass(0.2).continuous(axis=(0, 1, 0))

    robot = builder.build()

    gen = XACROGenerator(advanced_mode=True, generate_macros=True, extract_dimensions=True)
    out1 = gen.generate(robot)
    time.sleep(0.01)
    out2 = gen.generate(robot)

    assert out1 == out2
    assert "Date:" not in out1
    assert "Generated by: LinkForge\n" in out1


def test_generators_optional_version() -> None:
    """Verify generators support passing an explicit version keyword argument."""
    builder = _create_test_robot()
    robot = builder.build()
    robot.semantic = SemanticRobotDescription(
        robot_name="test_arm",
        virtual_joints=[VirtualJoint("world_joint", "fixed", "world", "base_link")],
        groups=[PlanningGroup("arm", joints=(robot.joints[0].name,))],
    )

    urdf_out = URDFGenerator().generate(robot, version="1.5.0")
    assert "Generated by: LinkForge v1.5.0" in urdf_out

    srdf_out = SRDFGenerator().generate(robot, version="1.5.0")
    assert "Generated by: LinkForge v1.5.0" in srdf_out

    xacro_out = XACROGenerator().generate(robot, version="1.5.0")
    assert "Generated by: LinkForge v1.5.0" in xacro_out
